const productos = [
  {
    id: 1,
    nombre: "Aspirina",
    categoria: "Medicamentos",
    imagen: "imagen1.jpg",
    precio: 5000,
    codigo: "Aaa00000",
    atributo1: "Dosificación: 500 mg por tableta",
    atributo2: "Alivio del dolor",
    atributo3: "Ingredientes activos: Ácido acetilsalicílico",
  },
  {
    id: 2,
    nombre: "Shampoo Pantene",
    categoria: "Cuidado Personal",
    imagen: "imagen2.jpg",
    precio: 12000,
    codigo: "Aaa00001",
    atributo1: "Tipo de producto: Shampoo",
    atributo2: "Para todo tipo de cabello",
    atributo3: "Ingredientes: Pantenol, Pro-Vitaminas",
  },
  {
    id: 3,
    nombre: "Labial Maybelline SuperStay",
    categoria: "Belleza",
    imagen: "imagen1.jpg",
    precio: 18000,
    codigo: "Aaa00002",
    atributo1: "Tipo de producto: Labial líquido",
    atributo2: "Larga duración",
    atributo3: "Rojo intenso",
  },
  {
    id: 4,
    nombre: "Pañales Huggies Natural Care",
    categoria: "Bebés",
    imagen: "imagen2.jpg",
    precio: 45000,
    codigo: "Aaa00003",
    atributo1: "Tipo de producto: Pañales desechables",
    atributo2: "Talla: Recién nacido (RN)",
    atributo3: "Material suave y absorbente",
  },
  {
    id: 5,
    nombre: "Multivitamínico Centrum",
    categoria: "Salud y Bienestar",
    imagen: "imagen1.jpg",
    precio: 30000,
    codigo: "Aaa00004",
    atributo1: "Tipo de producto: Suplemento vitamínico",
    atributo2: "Contiene vitaminas A, C, E, zinc, y más",
    atributo3: "Beneficios para la salud general",
  },
  {
    id: 6,
    nombre: "Alimento para gatos Whiskas",
    categoria: "Mascotas",
    imagen: "imagen2.jpg",
    precio: 25000,
    codigo: "Aaa00005",
    atributo1: "Alimento seco para gatos",
    atributo2: "Adulto",
    atributo3: "Sabor: Pollo y carne",
  },
  {
    id: 7,
    nombre: "Kit de Primeros Auxilios",
    categoria: "Primeros Auxilios",
    imagen: "imagen1.jpg",
    precio: 50000,
    codigo: "Aaa00006",
    atributo1: "Contenido: Vendas, gasas, alcohol, tijeras, etc.",
    atributo2: "Ideal para emergencias en el hogar y viajes",
    atributo3: "Tamaño compacto y portátil",
  },
  {
    id: 8,
    nombre: "Detergente Líquido Ariel",
    categoria: "Hogar",
    imagen: "imagen2.jpg",
    precio: 15000,
    codigo: "Aaa00007",
    atributo1: "Tipo de producto: Detergente líquido para ropa",
    atributo2: "Limpieza profunda",
    atributo3: "Fragancia fresca",
  },
  {
    id: 9,
    nombre: "Ibuprofeno",
    categoria: "Medicamentos",
    imagen: "imagen1.jpg",
    precio: 7000,
    codigo: "Aaa00008",
    atributo1: "Dosificación: 400 mg por tableta",
    atributo2: "Alivio del dolor y la inflamación",
    atributo3: "Ingredientes activos: Ibuprofeno",
  },
  {
    id: 10,
    nombre: "Crema humectante Nivea",
    categoria: "Cuidado Personal",
    imagen: "imagen2.jpg",
    precio: 10000,
    codigo: "Aaa00009",
    atributo1: "Tipo de producto: Crema humectante para el cuerpo",
    atributo2: "Hidratación intensiva",
    atributo3: "Ingredientes: Aceite de almendras y vitamina E",
  },
  {
    id: 11,
    nombre: "Mascarilla facial de arcilla L'Oréal",
    categoria: "Belleza",
    imagen: "imagen1.jpg",
    precio: 25000,
    codigo: "Aaa00010",
    atributo1: "Tipo de producto: Mascarilla facial de limpieza profunda",
    atributo2: "Purifica y matifica la piel",
    atributo3: "Con arcilla pura",
  },
  {
    id: 12,
    nombre: "Pañales Pampers",
    categoria: "Bebés",
    imagen: "imagen2.jpg",
    precio: 55000,
    codigo: "Aaa00011",
    atributo1: "Tipo de producto: Pañales desechables",
    atributo2: "Talla: Etapa 3 (5-9 kg)",
    atributo3: "Material suave y absorbente",
  },
  {
    id: 13,
    nombre: "Omega-3 Nature Made",
    categoria: "Salud y Bienestar",
    imagen: "imagen1.jpg",
    precio: 40000,
    codigo: "Aaa00012",
    atributo1: "Tipo de producto: Suplemento dietético",
    atributo2: "Contiene ácidos grasos omega-3",
    atributo3: "Beneficios para la salud cardiovascular",
  },
  {
    id: 14,
    nombre: "Comida para perros Pedigree",
    categoria: "Mascotas",
    imagen: "imagen2.jpg",
    precio: 35000,
    codigo: "Aaa00013",
    atributo1: "Tipo de producto: Alimento seco para perros adultos",
    atributo2: "Sabores variados (pollo, carne)",
    atributo3: "Enriquecido con vitaminas y minerales",
  },
  {
    id: 15,
    nombre: "Kit de Vendajes Adhesivos",
    categoria: "Primeros Auxilios",
    imagen: "imagen1.jpg",
    precio: 20000,
    codigo: "Aaa00014",
    atributo1: "Contenido: Vendajes de diferentes tamaños",
    atributo2: "Adhesivos y flexibles",
    atributo3: "Ideal para cortes y raspaduras",
  },
  {
    id: 16,
    nombre: "Ambientador Glade",
    categoria: "Hogar",
    imagen: "imagen2.jpg",
    precio: 8000,
    codigo: "Aaa00015",
    atributo1: "Tipo de producto: Ambientador en aerosol",
    atributo2: "Fragancia: Lavanda",
    atributo3: "Elimina los malos olores",
  },
  {
    id: 17,
    nombre: "Paracetamol",
    categoria: "Medicamentos",
    imagen: "imagen1.jpg",
    precio: 4000,
    codigo: "Aaa00016",
    atributo1: "Dosificación: 500 mg por tableta",
    atributo2: "Alivio del dolor y la fiebre",
    atributo3: "Ingredientes activos: Paracetamol",
  },
  {
    id: 18,
    nombre: "Desodorante Rexona",
    categoria: "Cuidado Personal",
    imagen: "imagen2.jpg",
    precio: 9000,
    codigo: "Aaa00017",
    atributo1: "Tipo de producto: Desodorante en aerosol",
    atributo2: "Protección contra el sudor y el mal olor",
    atributo3: "Fragancia: Fresh",
  },
  {
    id: 19,
    nombre: "Máscara de pestañas L'Oréal",
    categoria: "Belleza",
    imagen: "imagen1.jpg",
    precio: 15000,
    codigo: "Aaa00018",
    atributo1: "Tipo de producto: Máscara de pestañas",
    atributo2: "Volumen y alargamiento",
    atributo3: "Color: Negro intenso",
  },
  {
    id: 20,
    nombre: "Toallitas húmedas Huggies",
    categoria: "Bebés",
    imagen: "imagen2.jpg",
    precio: 18000,
    codigo: "Aaa00019",
    atributo1: "Tipo de producto: Toallitas húmedas para bebés",
    atributo2: "Dermatológicamente probadas",
    atributo3: "Suaves y resistentes",
  },
  {
    id: 21,
    nombre: "Calcio + Vitamina D Nature's Bounty",
    categoria: "Salud y Bienestar",
    imagen: "imagen1.jpg",
    precio: 28000,
    codigo: "Aaa00020",
    atributo1: "Tipo de producto: Suplemento de calcio",
    atributo2: "Fortalece los huesos y dientes",
    atributo3: "Con vitamina D para una mejor absorción",
  },
  {
    id: 22,
    nombre: "Alimento para peces Tetra",
    categoria: "Mascotas",
    imagen: "imagen2.jpg",
    precio: 12000,
    codigo: "Aaa00021",
    atributo1: "Tipo de producto: Alimento en escamas para peces tropicales",
    atributo2: "Enriquecido con proteínas y vitaminas",
    atributo3: "Ayuda a mantener colores vivos",
  },
  {
    id: 23,
    nombre: "Gel antiséptico para manos Germ-X",
    categoria: "Primeros Auxilios",
    imagen: "imagen1.jpg",
    precio: 6000,
    codigo: "Aaa00022",
    atributo1: "Tipo de producto: Gel desinfectante para manos",
    atributo2: "Mata el 99.99% de los gérmenes",
    atributo3: "Con aloe vera para una hidratación suave",
  },
  {
    id: 24,
    nombre: "Ambientador eléctrico Air Wick",
    categoria: "Hogar",
    imagen: "imagen2.jpg",
    precio: 10000,
    codigo: "Aaa00023",
    atributo1: "Tipo de producto: Ambientador eléctrico con recambio",
    atributo2: "Fragancia continua hasta por 45 días",
    atributo3: "Control de intensidad ajustable",
  },
  {
    id: 25,
    nombre: "Loratadina",
    categoria: "Medicamentos",
    imagen: "imagen1.jpg",
    precio: 8000,
    codigo: "Aaa00024",
    atributo1: "Dosificación: 10 mg por tableta",
    atributo2: "Alivio de los síntomas de alergia",
    atributo3: "Antihistamínico no sedante",
  },
  {
    id: 26,
    nombre: "Jabón Dove",
    categoria: "Cuidado Personal",
    imagen: "imagen1.jpg",
    precio: 5000,
    codigo: "Aaa00025",
    atributo1: "Tipo de producto: Jabón en barra",
    atributo2: "Hidratación suave para la piel",
    atributo3: "Fórmula con 1/4 de crema humectante",
  },
  {
    id: 27,
    nombre: "Esmalte de uñas Essie",
    categoria: "Belleza",
    imagen: "imagen2.jpg",
    precio: 12000,
    codigo: "Aaa00026",
    atributo1: "Tipo de producto: Esmalte de uñas",
    atributo2: "Colores variados y duraderos",
    atributo3: "Acabado brillante",
  },
  {
    id: 28,
    nombre: "Leche en polvo Nestlé Nido",
    categoria: "Bebés",
    imagen: "imagen1.jpg",
    precio: 40000,
    codigo: "Aaa00027",
    atributo1: "Tipo de producto: Leche en polvo para niños",
    atributo2: "Fórmula fortificada con vitaminas y minerales",
    atributo3: "Edad recomendada: 1 año en adelante",
  },
  {
    id: 29,
    nombre: "Melatonina Natrol",
    categoria: "Salud y Bienestar",
    imagen: "imagen2.jpg",
    precio: 20000,
    codigo: "Aaa00028",
    atributo1: "Tipo de producto: Suplemento de melatonina",
    atributo2: "Ayuda a conciliar el sueño",
    atributo3: "Liberación rápida",
  },
  {
    id: 30,
    nombre: "Alimento para pájaros Kaytee",
    categoria: "Mascotas",
    imagen: "imagen1.jpg",
    precio: 15000,
    codigo: "Aaa00029",
    atributo1: "Tipo de producto: Mezcla de semillas para aves",
    atributo2: "Enriquecido con vitaminas y minerales",
    atributo3: "Para pájaros pequeños y medianos",
  },
  {
    id: 31,
    nombre: "Termómetro digital",
    categoria: "Primeros Auxilios",
    imagen: "imagen2.jpg",
    precio: 18000,
    codigo: "Aaa00030",
    atributo1: "Tipo de producto: Termómetro oral y axilar",
    atributo2: "Lectura rápida y precisa",
    atributo3: "Pantalla LCD de fácil lectura",
  },
  {
    id: 32,
    nombre: "Ambientador en gel Febreze",
    categoria: "Hogar",
    imagen: "imagen1.jpg",
    precio: 10000,
    codigo: "Aaa00031",
    atributo1: "Tipo de producto: Ambientador en gel",
    atributo2: "Fragancia: Frescor de la mañana",
    atributo3: "Elimina los malos olores de forma duradera",
  },
  {
    id: 33,
    nombre: "Vitamina C",
    categoria: "Medicamentos",
    imagen: "imagen2.jpg",
    precio: 6000,
    codigo: "Aaa00032",
    atributo1: "Dosificación: 500 mg por tableta",
    atributo2: "Refuerza el sistema inmunológico",
    atributo3: "Contribuye a la salud de la piel",
  },
  {
    id: 34,
    nombre: "Enjuague bucal Listerine",
    categoria: "Cuidado Personal",
    imagen: "imagen1.jpg",
    precio: 8000,
    codigo: "Aaa00033",
    atributo1: "Tipo de producto: Enjuague bucal",
    atributo2: "Protección contra la placa y las bacterias",
    atributo3: "Frescor duradero",
  },
  {
    id: 35,
    nombre: "Paleta de sombras de ojos NYX",
    categoria: "Belleza",
    imagen: "imagen2.jpg",
    precio: 20000,
    codigo: "Aaa00034",
    atributo1: "Tipo de producto: Paleta de sombras de ojos",
    atributo2: "Variedad de colores y acabados",
    atributo3: "Pigmentación intensa",
  },
  {
    id: 36,
    nombre: "Toallitas húmedas Pampers",
    categoria: "Bebés",
    imagen: "imagen1.jpg",
    precio: 20000,
    codigo: "Aaa00035",
    atributo1: "Tipo de producto: Toallitas húmedas para bebés",
    atributo2: "Dermatológicamente probadas",
    atributo3: "Extra suaves y resistentes",
  },
  {
    id: 37,
    nombre: "Vitamina D3",
    categoria: "Salud y Bienestar",
    imagen: "imagen2.jpg",
    precio: 10000,
    codigo: "Aaa00036",
    atributo1: "Tipo de producto: Suplemento de vitamina D",
    atributo2: "Contribuye a la salud ósea y muscular",
    atributo3: "Absorción rápida y fácil",
  },
  {
    id: 38,
    nombre: "Alimento para conejos Oxbow",
    categoria: "Mascotas",
    imagen: "imagen1.jpg",
    precio: 30000,
    codigo: "Aaa00037",
    atributo1: "Tipo de producto: Alimento para conejos adultos",
    atributo2: "Alta fibra y nutrientes esenciales",
    atributo3: "Ayuda a mantener la salud dental",
  },
  {
    id: 39,
    nombre: "Esparadrapo adhesivo",
    categoria: "Primeros Auxilios",
    imagen: "imagen2.jpg",
    precio: 5000,
    codigo: "Aaa00038",
    atributo1: "Tipo de producto: Esparadrapo de tela",
    atributo2: "Flexible y resistente al agua",
    atributo3: "Corte fácil a medida",
  },
  {
    id: 40,
    nombre: "Ambientador en spray Ozium",
    categoria: "Hogar",
    imagen: "imagen1.jpg",
    precio: 12000,
    codigo: "Aaa00039",
    atributo1: "Tipo de producto: Ambientador en spray",
    atributo2: "Neutraliza y elimina olores desagradables",
    atributo3: "Fragancia original",
  },
  {
    id: 41,
    nombre: "Acetaminofén",
    categoria: "Medicamentos",
    imagen: "imagen2.jpg",
    precio: 6000,
    codigo: "Aaa00040",
    atributo1: "Dosificación: 500 mg por tableta",
    atributo2: "Alivio del dolor y la fiebre",
    atributo3: "Efecto rápido y duradero",
  },
  {
    id: 42,
    nombre: "Crema de afeitar Gillette",
    categoria: "Cuidado Personal",
    imagen: "imagen1.jpg",
    precio: 7000,
    codigo: "Aaa00041",
    atributo1: "Tipo de producto: Crema de afeitar para hombres",
    atributo2: "Suaviza la barba para un afeitado más cómodo",
    atributo3: "Hidrata la piel",
  },
  {
    id: 43,
    nombre: "Paleta de contorno e iluminador Anastasia Beverly Hills",
    categoria: "Belleza",
    imagen: "imagen2.jpg",
    precio: 40000,
    codigo: "Aaa00042",
    atributo1: "Tipo de producto: Paleta de contorno e iluminador",
    atributo2: "Tonos universales para esculpir y resaltar el rostro",
    atributo3: "Acabado natural y duradero",
  },
  {
    id: 44,
    nombre: "Leche de fórmula Similac",
    categoria: "Bebés",
    imagen: "imagen1.jpg",
    precio: 50000,
    codigo: "Aaa00043",
    atributo1: "Tipo de producto: Leche de fórmula infantil en polvo",
    atributo2: "Fórmula completa y equilibrada",
    atributo3: "Nutrición óptima para el crecimiento y desarrollo",
  },
  {
    id: 45,
    nombre: "Colágeno hidrolizado",
    categoria: "Salud y Bienestar",
    imagen: "imagen2.jpg",
    precio: 25000,
    codigo: "Aaa00044",
    atributo1: "Tipo de producto: Suplemento de colágeno en polvo",
    atributo2: "Promueve la salud de la piel, cabello y articulaciones",
    atributo3: "Fácil de mezclar en líquidos",
  },
  {
    id: 46,
    nombre: "Arena para gatos Tidy Cats",
    categoria: "Mascotas",
    imagen: "imagen1.jpg",
    precio: 20000,
    codigo: "Aaa00045",
    atributo1: "Tipo de producto: Arena aglomerante para gatos",
    atributo2: "Controla los olores de forma efectiva",
    atributo3: "Fácil de limpiar",
  },
  {
    id: 47,
    nombre: "Botiquín de viaje compacto",
    categoria: "Primeros Auxilios",
    imagen: "imagen2.jpg",
    precio: 30000,
    codigo: "Aaa00046",
    atributo1: "Contenido: Vendajes, gasas, alcohol, tijeras, etc.",
    atributo2: "Diseño compacto y portátil",
    atributo3: "Ideal para viajes y actividades al aire libre",
  },
  {
    id: 48,
    nombre: "Limpiador multiusos Ajax",
    categoria: "Hogar",
    imagen: "imagen1.jpg",
    precio: 8000,
    codigo: "Aaa00047",
    atributo1: "Tipo de producto: Limpiador líquido multiusos",
    atributo2: "Elimina la suciedad y la grasa",
    atributo3: "Fragancia fresca de limón",
  },
  {
    id: 49,
    nombre: "",
    categoria: "Primeros Auxilios",
    imagen: "imagen2.jpg",
    precio: 5000,
    codigo: "Aaa00048",
    atributo1: "Tipo de producto: Tijeras de seguridad con punta roma",
    atributo2: "Ideal para cortar vendajes y prendas de vestir",
    atributo3: "Mango ergonómico para un agarre cómodo",
  },
  {
    id: 50,
    nombre: "Desinfectante para superficies Lysol",
    categoria: "Hogar",
    imagen: "imagen1.jpg",
    precio: 12000,
    codigo: "Aaa00049",
    atributo1: "Tipo de producto: Aerosol desinfectante",
    atributo2: "Elimina el 99.9% de gérmenes y bacterias",
    atributo3: "Aroma fresco y limpio",
  },
];

const productosPorPagina = 15;
let paginaActual = 1;

// Función para mostrar los productos en la página actual
function mostrarProductos() {
  const startIndex = (paginaActual - 1) * productosPorPagina;
  const endIndex = paginaActual * productosPorPagina;
  const productosHTML = productos
    .slice(startIndex, endIndex)
    .map((producto) => {
      return `
            <div class="producto">
                <h3>${producto.nombre}</h3>
                <p><strong>Categoría:</strong> ${producto.categoria}</p>
                <img src="${producto.imagen}" alt="Imagen del producto ${producto.nombre}">
                <p><strong>Precio:</strong> $${producto.precio}</p>
                <p><strong>Código de Producto:</strong> ${producto.codigo}</p>
                <p><strong>Atributo 1:</strong> ${producto.atributo1}</p>
                <p><strong>Atributo 2:</strong> ${producto.atributo2}</p>
                <p><strong>Atributo 3:</strong> ${producto.atributo3}</p>
            </div>
        `;
    })
    .join("");
  document.getElementById("productos").innerHTML = productosHTML;

  // Actualizar el número de página en el label
  const pageLabel = document.getElementById("num");
  pageLabel.textContent = `Página ${paginaActual}`;

  // Habilitar/deshabilitar botones de paginación
  const prevPageBtn = document.getElementById("prevPageBtn");
  const nextPageBtn = document.getElementById("nextPageBtn");
  prevPageBtn.disabled = paginaActual === 1;
  nextPageBtn.disabled = endIndex >= productos.length;
}

// Función para ir a la página anterior
function paginaAnterior() {
  if (paginaActual > 1) {
    paginaActual--;
    mostrarProductos();
  }
}

// Función para ir a la página siguiente
function paginaSiguiente() {
  paginaActual++;
  mostrarProductos();
}

// Función para redirigir a la página de registro de productos
function redirectRegistro() {
  window.location.href = "./Pages/registro.html";
}

// Función para redirigir a la página de filtros de búsqueda
function redirectFiltros() {
  window.location.href = "./Pages/filtros.html";
}

// Cargar los productos iniciales al cargar la página
mostrarProductos();
